INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK,ALATITUDE,ALONGITUDE)
VALUES (1,'개나리SK뷰','풀옵션된 전망좋은 남향, 조용하고 깨끗한 입주가능 집','.','매매',168000,0,0,0,'160.22','127.27',501,25,20,'남향','2개월 후'
,'계단식',4,2,0,NOW(),NOW(),true,true,true,true,true,true,true,true,'37.500961', '127.050116');


INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK,ALATITUDE,ALONGITUDE)
VALUES (1,'개나리SK뷰','확장 풀옵션, 전망 채광좋은 급매물','도성초 진선여중고학군, 선릉 역세권으로 교통편리함.','매매',170000,0,0,0,'160.22','127.27',501,25,17,'남향','즉시입주'
,'계단식',4,2,0,NOW(),NOW(),true,true,false,true,false,true,false,true,'37.500961', '127.050116');


INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK,ALATITUDE,ALONGITUDE)
VALUES (1,'개나리SK뷰','입주 3년차 확장 시스템에어콘등 조용하고 전망 좋습니다','도성초 진선여중고 학군입니다. 선릉 역세권으로 교통이 편리합니다.','매매',168000,0,0,0,'160.22','127.27',503,25,7,'남향','즉시입주'
,'계단식',4,2,0,NOW(),NOW(),false,true,false,true,false,true,false,false,'37.501771', '127.049726');


INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK,ALATITUDE,ALONGITUDE)
VALUES (1,'개나리SK뷰','확장 풀옵션, 전망 채광좋은 귀한 전세매물','도성초 진선여중고 학군입니다. 선릉 역세권으로 교통이 편리한단지.','전세',0,124000,0,0,'160.22','127.27',501,25,6,'남향','즉시입주'
,'계단식',4,2,0,NOW(),NOW(),false,true,false,true,false,true,false,false,'37.500961', '127.050116');


INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK,ALATITUDE,ALONGITUDE)
VALUES (1,'개나리SK뷰','확장 전망 채광좋은 급매물입니다.','도성초 진선여중고 학군입니다. 선릉 역세권으로 교통이 편리한단지.','월세',0,0,10000 ,310,'112.96','84.99',502,25,20,'남향','즉시입주'
,'계단식',3,2,0,NOW(),NOW(),false,true,false,true,false,true,false,false,'37.501404', '127.049900');


INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK,ALATITUDE,ALONGITUDE)
VALUES (1,'개나리SK뷰','확장 옵션, 로얄층 전망 좋은 저렴한 월세','도성초 진선여중고 학군입니다. 선릉 역세권으로 교통이 편리한단지.','월세',0,0,5000,330,'112.96','84.99',503,25,14,'남향','즉시입주'
,'계단식',3,2,0,NOW(),NOW(),false,true,false,true,true,true,false,true,'37.501771', '127.049726');