drop table PHOTOS;
drop table APARTMENTS;
drop table COMPLEXES;


-- 아파트단지
CREATE TABLE `COMPLEXES` (
  `CNO`               INTEGER      NOT NULL COMMENT '아파트단지번호', -- 아파트단지번호
  `CNAME`             VARCHAR(255) NOT NULL COMMENT '아파트단지이름', -- 아파트단지이름
  `ADDRESS`           VARCHAR(255) NOT NULL COMMENT '주소', -- 주소
  `BLOCK_TOTAL`       INTEGER      NOT NULL COMMENT '총동수', -- 총동수
  `DOOR_TOTAL`        INTEGER      NOT NULL COMMENT '총세대수', -- 총세대수
  `PARK_TOTAL`        INTEGER      NOT NULL COMMENT '총주차대수', -- 총주차대수
  `HIGHEST_TIER`      INTEGER      NOT NULL COMMENT '최고층', -- 최고층
  `LOWEST_TIER`       INTEGER      NOT NULL COMMENT '최저층', -- 최저층
  `HEAT_SYSTEM`       VARCHAR(255) NOT NULL COMMENT '난방방식', -- 난방방식
  `HEAT_FUEL`         VARCHAR(255) NOT NULL COMMENT '난방연료', -- 난방연료
  `FLOOR_AREA_RATION` VARCHAR(255) NOT NULL COMMENT '용적률', -- 용적률
  `COMPANY_NAME`      VARCHAR(255) NOT NULL COMMENT '건설사명', -- 건설사명
  `MOVE_DATE`         VARCHAR(50)  NOT NULL COMMENT '입주년일', -- 입주년일
  `COMPLETE_DATE`     VARCHAR(50)  NOT NULL COMMENT '준공년일' -- 준공년일
)
COMMENT '아파트단지';

-- 아파트단지
ALTER TABLE `COMPLEXES`
  ADD CONSTRAINT `PK_COMPLEXES` -- 아파트단지 기본키
    PRIMARY KEY (
      `CNO` -- 아파트단지번호
    );

ALTER TABLE `COMPLEXES`
  MODIFY COLUMN `CNO` INTEGER NOT NULL AUTO_INCREMENT COMMENT '아파트단지번호';

-- 아파트
CREATE TABLE `APARTMENTS` (
  `ANO`             INTEGER      NOT NULL COMMENT '아파트번호', -- 아파트번호
  `CNO`             INTEGER      NOT NULL COMMENT '아파트단지번호', -- 아파트단지번호
  `ANAME`           VARCHAR(255) NULL     COMMENT '아파트이름', -- 아파트이름
  `TITLE`           VARCHAR(255) NULL     COMMENT '제목', -- 제목
  `CONTENT`         TEXT         NULL     COMMENT '내용', -- 내용
  `BUY_TYPE`        VARCHAR(255) NULL     COMMENT '매물구분', -- 매물구분
  `SALE_PRICE`      INTEGER      NULL     COMMENT '매매가격', -- 매매가격
  `RENT_DEPOSIT`    INTEGER      NULL     COMMENT '전세보증금', -- 전세보증금
  `MRENT_DEPOSIT`   INTEGER      NULL     COMMENT '월세보증금', -- 월세보증금
  `MRENT_PRICE`     INTEGER      NULL     COMMENT '월세', -- 월세
  `SUPPLY_AREA`     VARCHAR(50)  NULL     COMMENT '공급면적', -- 공급면적
  `EXCLUSIVE_AREA`  VARCHAR(50)  NULL     COMMENT '전용면적', -- 전용면적
  `BLOCK`           INTEGER      NULL     COMMENT '동', -- 동
  `TIER_TOTAL`      INTEGER      NULL     COMMENT '총층', -- 총층
  `TIER`            INTEGER      NULL     COMMENT '층', -- 층
  `DIRECTION`       VARCHAR(100) NULL     COMMENT '방향', -- 방향
  `EXPECT_DATE`     VARCHAR(50)  NULL     COMMENT '입주예정일', -- 입주예정일
  `ENTRANCE_STRUCT` VARCHAR(255) NULL     COMMENT '현관구조', -- 현관구조
  `ROOM_NUMBER`     INTEGER      NULL     COMMENT '방갯수', -- 방갯수
  `BATH_NUMBER`     INTEGER      NULL     COMMENT '욕실갯수', -- 욕실갯수
  `LIVING_NUMBER`   INTEGER      NULL     COMMENT '거실갯수', -- 거실갯수
  `CREATE_DATE`     DATETIME     NOT NULL COMMENT '등록날짜', -- 등록날짜
  `MODIFY_DATE`     DATETIME     NOT NULL COMMENT '수정날짜', -- 수정날짜
  `BALCONY`         BOOLEAN      NOT NULL COMMENT '발코니', -- 발코니
  `WALLPAPER`       BOOLEAN      NOT NULL COMMENT '벽지', -- 벽지
  `BATHROOM`        BOOLEAN      NOT NULL COMMENT '화장실', -- 화장실
  `CEILING`         BOOLEAN      NOT NULL COMMENT '천장', -- 천장
  `FLOOR`           BOOLEAN      NOT NULL COMMENT '마루', -- 마루
  `KITCHEN`         BOOLEAN      NOT NULL COMMENT '부엌', -- 부엌
  `ENTRANCE`        BOOLEAN      NOT NULL COMMENT '전실', -- 전실
  `SHOE_RACK`       BOOLEAN      NOT NULL COMMENT '신발장' -- 신발장
)
COMMENT '아파트';

-- 아파트
ALTER TABLE `APARTMENTS`
  ADD CONSTRAINT `PK_APARTMENTS` -- 아파트 기본키
    PRIMARY KEY (
      `ANO`, -- 아파트번호
      `CNO`  -- 아파트단지번호
    );

ALTER TABLE `APARTMENTS`
  MODIFY COLUMN `ANO` INTEGER NOT NULL AUTO_INCREMENT COMMENT '아파트번호';

-- 사진
CREATE TABLE `PHOTOS` (
  `PNO`        INTEGER      NOT NULL COMMENT '사진번호', -- 사진번호
  `ANO`        INTEGER      NOT NULL COMMENT '아파트번호', -- 아파트번호
  `CNO`        INTEGER      NOT NULL COMMENT '아파트단지번호', -- 아파트단지번호
  `PHOTO_PATH` VARCHAR(255) NOT NULL COMMENT '경로' -- 경로
)
COMMENT '사진';

-- 사진
ALTER TABLE `PHOTOS`
  ADD CONSTRAINT `PK_PHOTOS` -- 사진 기본키
    PRIMARY KEY (
      `PNO`, -- 사진번호
      `ANO`, -- 아파트번호
      `CNO`  -- 아파트단지번호
    );

ALTER TABLE `PHOTOS`
  MODIFY COLUMN `PNO` INTEGER NOT NULL AUTO_INCREMENT COMMENT '사진번호';

-- 아파트
ALTER TABLE `APARTMENTS`
  ADD CONSTRAINT `FK_COMPLEXES_TO_APARTMENTS` -- 아파트단지 -> 아파트
    FOREIGN KEY (
      `CNO` -- 아파트단지번호
    )
    REFERENCES `COMPLEXES` ( -- 아파트단지
      `CNO` -- 아파트단지번호
    );

-- 사진
ALTER TABLE `PHOTOS`
  ADD CONSTRAINT `FK_APARTMENTS_TO_PHOTOS` -- 아파트 -> 사진
    FOREIGN KEY (
      `ANO`, -- 아파트번호
      `CNO`  -- 아파트단지번호
    )
    REFERENCES `APARTMENTS` ( -- 아파트
      `ANO`, -- 아파트번호
      `CNO`  -- 아파트단지번호
    );
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    
    
    
    
INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('개나리SK뷰','서울 강남구 역삼동 716-3',3,247,397,25,25,'지역난방','열병합','257.67','에스케이건설','2012년 08월','2012년 08월 17일');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('동부센트레빌','서울 강남구 역삼동 716',1,206,208,21,19,'중앙난방','도시가스','350.69','동부건설','1998년 04월','1998년 04월 21일');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('래미안펜타빌','서울 강남구 역삼동 713-7',5,288,665,24,14,'지역난방','열병합','273.98','삼성물산','2007년 11월','2007년 11월 30일');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('역삼IPARK','서울 강남구 역삼동 713-11',7,541,914,21,12,'지역난방','열병합','273.98','현대산업개발','2006년 09월','2006년 09월 28일');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('개나리4차','서울 강남구 역삼동 712-3',3,264,130,12,12,'지역난방','열병합','235.40','삼호','1979년 01월','1979년 02월 23일');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('역삼자이','서울 강남구 역삼동 711',3,408,615,31,23,'지역난방','열병합','299.96','지에스건설','2016년 06월 23일','2016년 06월');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('현대까르띠에710','서울 강남구 역삼동 710',3,137,340,24,10,'중앙난방','도시가스','298.54','현대건설','2001년 11월','2001년 11월 09일');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('테헤란아이파크','서울 강남구 역삼동 709',6,411,589,25,7,'지역난방','열병합','255.62','현대산업개발','2014년 01월 29일','2014년 01월');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('개나리푸르지오','서울 강남구 역삼동 755-1',5,332,552,24,12,'지역난방','열병합','275.36','대우건설','2006년 08월','2006년 08월 14일');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('역삼e-편한세상','서울 강남구 역삼동 755-4',12,840,852,25,15,'지역난방','열병합','282.26','대림산업','2005년 12월','2005년 12월 16일');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('개나리래미안','서울 강남구 역삼동 754',7,438,788,22,11,'지역난방','열병합','273.25','삼성물산','2006년 08월','2006년 08월 31일');

INSERT INTO COMPLEXES(CNAME,ADDRESS,BLOCK_TOTAL,DOOR_TOTAL,PARK_TOTAL,HIGHEST_TIER,LOWEST_TIER,HEAT_SYSTEM,HEAT_FUEL,FLOOR_AREA_RATION,COMPANY_NAME,MOVE_DATE,COMPLETE_DATE)
VALUES ('역삼푸르지오','서울 강남구 역삼동 754-1',11,738,753,24,15,'지역난방','열병합','283.18','대우건설','2005년 12월','2006년 01월 02일');



INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK)
VALUES (1,'개나리SK뷰','풀옵션된 전망좋은 남향, 조용하고 깨끗한 입주가능 집','.','매매',168000,0,0,0,'160.22','127.27',501,25,20,'남향','2개월 후'
,'계단식',4,2,0,NOW(),NOW(),true,true,true,true,true,true,true,true);


INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK)
VALUES (1,'개나리SK뷰','확장 풀옵션, 전망 채광좋은 급매물','도성초 진선여중고학군, 선릉 역세권으로 교통편리함.','매매',170000,0,0,0,'160.22','127.27',501,25,17,'남향','즉시입주'
,'계단식',4,2,0,NOW(),NOW(),true,true,false,true,false,true,false,true);


INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK)
VALUES (1,'개나리SK뷰','입주 3년차 확장 시스템에어콘등 조용하고 전망 좋습니다','도성초 진선여중고 학군입니다. 선릉 역세권으로 교통이 편리합니다.','매매',168000,0,0,0,'160.22','127.27',503,25,7,'남향','즉시입주'
,'계단식',4,2,0,NOW(),NOW(),false,true,false,true,false,true,false,false);


INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK)
VALUES (1,'개나리SK뷰','확장 풀옵션, 전망 채광좋은 귀한 전세매물','도성초 진선여중고 학군입니다. 선릉 역세권으로 교통이 편리한단지.','전세',0,124000,0,0,'160.22','127.27',501,25,6,'남향','즉시입주'
,'계단식',4,2,0,NOW(),NOW(),false,true,false,true,false,true,false,false);


INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK)
VALUES (1,'개나리SK뷰','확장 전망 채광좋은 급매물입니다.','도성초 진선여중고 학군입니다. 선릉 역세권으로 교통이 편리한단지.','월세',0,0,10000 ,310,'112.96','84.99',502,25,20,'남향','즉시입주'
,'계단식',3,2,0,NOW(),NOW(),false,true,false,true,false,true,false,false);


INSERT INTO APARTMENTS(CNO,ANAME,TITLE,CONTENT,BUY_TYPE,SALE_PRICE,RENT_DEPOSIT,MRENT_DEPOSIT,MRENT_PRICE
,SUPPLY_AREA,EXCLUSIVE_AREA,BLOCK,TIER_TOTAL,TIER,DIRECTION,EXPECT_DATE,ENTRANCE_STRUCT,ROOM_NUMBER,BATH_NUMBER
,LIVING_NUMBER,CREATE_DATE,MODIFY_DATE,BALCONY,WALLPAPER,BATHROOM,CEILING,FLOOR,KITCHEN,ENTRANCE,SHOE_RACK)
VALUES (1,'개나리SK뷰','확장 옵션, 로얄층 전망 좋은 저렴한 월세','도성초 진선여중고 학군입니다. 선릉 역세권으로 교통이 편리한단지.','월세',0,0,5000,330,'112.96','84.99',503,25,14,'남향','즉시입주'
,'계단식',3,2,0,NOW(),NOW(),false,true,false,true,true,true,false,true);

    